---
name: arduino-lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # https://github.com/actions/checkout
      - uses: arduino/arduino-lint-action@v1
        # https://github.com/arduino/arduino-lint-action
        with:
          library-manager: update
          compliance: strict
